// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Spotify  _ControllerV2

#ifndef _SPOTIFY___CONTROLLERV2_UI_H
#define _SPOTIFY___CONTROLLERV2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_ImgCover.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg_png);    // assets/BG.png
LV_IMG_DECLARE(ui_img_play_pause_png);    // assets/PLAY_PAUSE.png
LV_IMG_DECLARE(ui_img_coveralbum1_png);    // assets/CoverAlbum1.png
LV_IMG_DECLARE(ui_img_104607339);    // assets/PLAY_PAUSE (2).png
LV_IMG_DECLARE(ui_img_next_png);    // assets/NEXT.png
LV_IMG_DECLARE(ui_img_prev_png);    // assets/PREV.png

// FONTS
LV_FONT_DECLARE(ui_font_FontArtis24);
LV_FONT_DECLARE(ui_font_FontJudul48);
LV_FONT_DECLARE(ui_font_FontJepang24);
LV_FONT_DECLARE(ui_font_FontJepang48);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
