// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Spotify  _ControllerV2

#include "ui.h"

lv_obj_t * uic_SliderProgress;
lv_obj_t * uic_SongTime;
lv_obj_t * uic_BtnPrev;
lv_obj_t * uic_BtnNext;
lv_obj_t * uic_BtnPlay;
lv_obj_t * uic_ImgCover1;
lv_obj_t * uic_BtnPlay;
lv_obj_t * uic_LabelArtis;
lv_obj_t * uic_LabelJudul;
lv_obj_t * uic_ImgCover;
lv_obj_t * ui_ImgCover = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_LabelJudul = NULL;
lv_obj_t * ui_LabelArtis = NULL;
lv_obj_t * ui_BtnPlay = NULL;
lv_obj_t * ui_ImgCover1 = NULL;
lv_obj_t * ui_BtnPause = NULL;
lv_obj_t * ui_BtnNext = NULL;
lv_obj_t * ui_BtnPrev = NULL;
lv_obj_t * ui_SongTime = NULL;
lv_obj_t * ui_SliderProgress = NULL;
// event funtions

// build funtions

void ui_ImgCover_screen_init(void)
{
    ui_ImgCover = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ImgCover, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ImgCover, lv_color_hex(0x010060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgCover, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_ImgCover);
    lv_img_set_src(ui_Image1, &ui_img_bg_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Image1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelJudul = lv_label_create(ui_ImgCover);
    lv_obj_set_width(ui_LabelJudul, 310);
    lv_obj_set_height(ui_LabelJudul, 60);
    lv_obj_set_x(ui_LabelJudul, 210);
    lv_obj_set_y(ui_LabelJudul, -80);
    lv_obj_set_align(ui_LabelJudul, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelJudul, "Song Title");
    lv_obj_set_style_text_align(ui_LabelJudul, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelJudul, &ui_font_FontJudul48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelArtis = lv_label_create(ui_ImgCover);
    lv_obj_set_width(ui_LabelArtis, 310);
    lv_obj_set_height(ui_LabelArtis, 25);
    lv_obj_set_x(ui_LabelArtis, 210);
    lv_obj_set_y(ui_LabelArtis, -20);
    lv_obj_set_align(ui_LabelArtis, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArtis, "Artist");
    lv_obj_set_style_text_align(ui_LabelArtis, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelArtis, &ui_font_FontArtis24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPlay = lv_imgbtn_create(ui_ImgCover);
    lv_imgbtn_set_src(ui_BtnPlay, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_play_pause_png, NULL);
    lv_obj_set_width(ui_BtnPlay, 80);
    lv_obj_set_height(ui_BtnPlay, 80);
    lv_obj_set_x(ui_BtnPlay, 210);
    lv_obj_set_y(ui_BtnPlay, 70);
    lv_obj_set_align(ui_BtnPlay, LV_ALIGN_CENTER);

    ui_ImgCover1 = lv_img_create(ui_ImgCover);
    lv_img_set_src(ui_ImgCover1, &ui_img_coveralbum1_png);
    lv_obj_set_width(ui_ImgCover1, 350);
    lv_obj_set_height(ui_ImgCover1, 350);
    lv_obj_set_x(ui_ImgCover1, -180);
    lv_obj_set_y(ui_ImgCover1, -15);
    lv_obj_set_align(ui_ImgCover1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgCover1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgCover1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnPause = lv_imgbtn_create(ui_ImgCover);
    lv_imgbtn_set_src(ui_BtnPause, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_104607339, NULL);
    lv_obj_set_width(ui_BtnPause, 80);
    lv_obj_set_height(ui_BtnPause, 80);
    lv_obj_set_x(ui_BtnPause, 210);
    lv_obj_set_y(ui_BtnPause, 70);
    lv_obj_set_align(ui_BtnPause, LV_ALIGN_CENTER);

    ui_BtnNext = lv_imgbtn_create(ui_ImgCover);
    lv_imgbtn_set_src(ui_BtnNext, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_next_png, NULL);
    lv_obj_set_width(ui_BtnNext, 80);
    lv_obj_set_height(ui_BtnNext, 80);
    lv_obj_set_x(ui_BtnNext, 320);
    lv_obj_set_y(ui_BtnNext, 70);
    lv_obj_set_align(ui_BtnNext, LV_ALIGN_CENTER);

    ui_BtnPrev = lv_imgbtn_create(ui_ImgCover);
    lv_imgbtn_set_src(ui_BtnPrev, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_prev_png, NULL);
    lv_obj_set_width(ui_BtnPrev, 80);
    lv_obj_set_height(ui_BtnPrev, 80);
    lv_obj_set_x(ui_BtnPrev, 90);
    lv_obj_set_y(ui_BtnPrev, 70);
    lv_obj_set_align(ui_BtnPrev, LV_ALIGN_CENTER);

    ui_SongTime = lv_label_create(ui_ImgCover);
    lv_obj_set_width(ui_SongTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SongTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SongTime, -180);
    lv_obj_set_y(ui_SongTime, 180);
    lv_obj_set_align(ui_SongTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SongTime, "00:00 / 00:00");
    lv_obj_set_style_text_font(ui_SongTime, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderProgress = lv_arc_create(ui_ImgCover);
    lv_obj_set_width(ui_SliderProgress, 350);
    lv_obj_set_height(ui_SliderProgress, 350);
    lv_obj_set_x(ui_SliderProgress, -180);
    lv_obj_set_y(ui_SliderProgress, -15);
    lv_obj_set_align(ui_SliderProgress, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_SliderProgress, 50);
    lv_arc_set_bg_angles(ui_SliderProgress, 110, 70);

    lv_obj_set_style_arc_color(ui_SliderProgress, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SliderProgress, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderProgress, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderProgress, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    uic_ImgCover = ui_ImgCover;
    uic_LabelJudul = ui_LabelJudul;
    uic_LabelArtis = ui_LabelArtis;
    uic_BtnPlay = ui_BtnPlay;
    uic_ImgCover1 = ui_ImgCover1;
    uic_BtnPlay = ui_BtnPause;
    uic_BtnNext = ui_BtnNext;
    uic_BtnPrev = ui_BtnPrev;
    uic_SongTime = ui_SongTime;
    uic_SliderProgress = ui_SliderProgress;

}

void ui_ImgCover_screen_destroy(void)
{
    if(ui_ImgCover) lv_obj_del(ui_ImgCover);

    // NULL screen variables
    uic_ImgCover = NULL;
    ui_ImgCover = NULL;
    ui_Image1 = NULL;
    uic_LabelJudul = NULL;
    ui_LabelJudul = NULL;
    uic_LabelArtis = NULL;
    ui_LabelArtis = NULL;
    uic_BtnPlay = NULL;
    ui_BtnPlay = NULL;
    uic_ImgCover1 = NULL;
    ui_ImgCover1 = NULL;
    uic_BtnPlay = NULL;
    ui_BtnPause = NULL;
    uic_BtnNext = NULL;
    ui_BtnNext = NULL;
    uic_BtnPrev = NULL;
    ui_BtnPrev = NULL;
    uic_SongTime = NULL;
    ui_SongTime = NULL;
    uic_SliderProgress = NULL;
    ui_SliderProgress = NULL;

}
