// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Spotify  _ControllerV2

#ifndef UI_IMGCOVER_H
#define UI_IMGCOVER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ImgCover
extern void ui_ImgCover_screen_init(void);
extern void ui_ImgCover_screen_destroy(void);
extern lv_obj_t * ui_ImgCover;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_LabelJudul;
extern lv_obj_t * ui_LabelArtis;
extern lv_obj_t * ui_BtnPlay;
extern lv_obj_t * ui_ImgCover1;
extern lv_obj_t * ui_BtnPause;
extern lv_obj_t * ui_BtnNext;
extern lv_obj_t * ui_BtnPrev;
extern lv_obj_t * ui_SongTime;
extern lv_obj_t * ui_SliderProgress;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ImgCover;
extern lv_obj_t * uic_LabelJudul;
extern lv_obj_t * uic_LabelArtis;
extern lv_obj_t * uic_BtnPlay;
extern lv_obj_t * uic_ImgCover1;
extern lv_obj_t * uic_BtnPlay;
extern lv_obj_t * uic_BtnNext;
extern lv_obj_t * uic_BtnPrev;
extern lv_obj_t * uic_SongTime;
extern lv_obj_t * uic_SliderProgress;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

